max_rf_z: 90
min_rf_z: 10

## Feedback Gain
# virtual (x,y,z) (Rx,Ry, Rz) 
# right abduction, hip, knee 
# left abduction, hip, knee 

Kp: [0, 0, 0, 0, 0, 0, 200, 200, 200, 200, 200, 200]
Kd: [0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5]

