planner_name: velocity_reversal_lipm
swing_height: 0.12
push_down_height: 0.002
#push_down_height: 0.02
default_target_foot_location: [-0.08, 0.10, 0.0]
swing_jpos_delta: [ 0.0, -0.145, 0.4]

## Feedback Gain
# config x6
# Kp: [ 50, 50, 50, 50, 50, 50]
# Kd: [ 5, 5, 5, 5, 5, 5]

Kp: [ 100, 100, 100, 100, 100, 100]
Kd: [ 10, 10, 10, 10, 10, 10]

# body_pt_offset: [-0.02, -0.0055]
body_pt_offset: [0.01, -0.007]
swing_time_reduction: 0.0
foot_landing_offset: [-0.0, 0.]

initial_planning: false
