planner_name: velocity_reversal_lipm
swing_height: 0.10
push_down_height: 0.0
#push_down_height: 0.02
default_target_foot_location: [0.0, 0.1, 0.0]

## Feedback Gain
# virtual (x, y, z, Rx, Ry, Rz) config x6
Kp: [ 0, 0, 0, 0, 0, 600, 600, 600, 600, 600, 600]
Kd: [ 0, 0, 0, 0, 0,  50,  50,  50,  50,  50,  50]

gain_decreasing_ratio: 1.0
gain_decreasing_period_portion: 0.0

