planner_name: velocity_reversal_lipm
swing_height: 0.13
push_down_height: 0.0
#push_down_height: 0.02
default_target_foot_location: [0.0, -0.12, 0.0]

## Feedback Gain
# virtual (x, y, z, Rx, Ry, Rz) config x6
# Kp: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
# Kd: [ 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0]

#Kp: [ 0, 0, 0, 0, 0, 0, 300, 300, 300, 300, 300, 300]
#Kd: [ 0, 0, 0, 0, 0, 0, 15,  15,  15,  15,  15,  15]

# stance(left) & swing (right)
Kp: [ 0, 0, 0, 0, 0, 0, 150, 150, 150, 50, 50, 50]
Kd: [ 0, 0, 0, 0, 0, 0, 10,  10,  10,  5,  5,  5]

gain_decreasing_ratio: 1.0
gain_decreasing_period_portion: 0.0

